### PR TITLE
Added images. Reads image elements from the feed if any.

### PR DESCRIPTION
**Pull request by keesdewit82**

### CODE REVIEW

**Comment by RobThree** [comment]
Hi and thanks @keesdewit82! 

Although I like your idea, I do have a few nitpicks with this PR. If you could change those I will merge this PR.

- The use of [`ICollection`](https://github.com/RobThree/SimpleFeedReader/pull/4/files#diff-1731588a0d36aaf7652b0b408e001bfdR41) is not in line with the rest; I think `IEnumerable` should be used
- [`imageUri` and `GetFeedItemImage`](https://github.com/RobThree/SimpleFeedReader/pull/4/files#diff-074c29a183e6eec8ff86b1489783fe90R49) should be plural; the former contains (possibly) `N` items, the latter returns (possibly) `N` items (you did use Images (plural) [here](https://github.com/RobThree/SimpleFeedReader/pull/4/files#diff-074c29a183e6eec8ff86b1489783fe90R60)).
- A unittest (at least _one_) with images should be added / implemented

Having said that; I do appreciate the PR. The project is due for some 'refactoring' anyway; so if you can't be bothered, no hard feelings; I may change the PR myself and then merge.

**Comment by keesdewit82** [comment]
Hi RobThree,

I have changed the code accordingly.

**Comment by keesdewit82** [comment]
I think that AppVeyor cannot handle C# 6 language features. It errors over the collection initializer that I used: https://github.com/keesdewit82/SimpleFeedReader/blob/master/SimpleFeedReader/FeedItem.cs#L41

**Comment by RobThree** [comment]
It's not AppVeyor at fault here; it is/was the solution file being VS2013. I [updated the solution file](https://github.com/RobThree/SimpleFeedReader/commit/9ca5816f24dfc2821df2e0b19c11b2cbacb0f152) and, as you can see, the build now passes. I'll merge/release a new version soon. Again: thanks for the PR!

**Comment by RobThree** [comment]
Just released [1.0.5](https://www.nuget.org/packages/SimpleFeedReader/1.0.5). Thanks! 👍

**Comment by theNailz** [comment]
Bumping this issue; this does appear to be a problem in my VS (2015) project:

```Property or indexer 'FeedItem.Images' cannot be assigned to -- it is read only```

**Comment by RobThree** [comment]
Can you please provide a testcase to reproduce the problem?

**Comment by keesdewit82** [comment]
It has no setter because collection properties should not have setters.

**Comment by theNailz** [comment]
I have tried copying the existing Normalizer to my own (Implementing IFeedItemNormalizer), but the same code in my Normalizer doesn't compile. I'll try to provide a test case tonight.

**Comment by RobThree** [comment]
Makes sense. From the hip.... I guess making it [protected instead of internal](https://github.com/RobThree/SimpleFeedReader/blob/master/SimpleFeedReader/FeedItem.cs#L41) should probably solve it?

**Comment by theNailz** [comment]
Yep, that way we can pass it in through the constructor, and set it from there.

**Comment by keesdewit82** [comment]
Protected would make sense if you use FeedItem as base class. FeedItem is not sealed so you should be allowed to set the Images property from the inheriting class, thus making protected the right access modifier in this case.

**Comment by RobThree** [comment]
So we all agree on making it `protected`? I'm also fine making it `public`; the rest of the properties have public setters too so I don't think it's that big of a problem.

**Comment by keesdewit82** [comment]
I would make it protected. It also depends on what guidelines you are used to work with. This is one of them https://msdn.microsoft.com/en-us/library/ms182327.aspx

**Comment by keesdewit82** [comment]
Also @theNailz Small advice: You should not be passing stateful objects through the constructor.

**Comment by RobThree** [comment]
Protected won't suffice since even the `DefaultFeedItemNormalizer` won't be able to [create a FeedItem](https://github.com/RobThree/SimpleFeedReader/blob/master/SimpleFeedReader/DefaultFeedItemNormalizer.cs#L58).

**Comment by RobThree** [comment]
a063de3a41f7eea4992efb090c6313966d285e10

**Comment by keesdewit82** [comment]
No problem. Making it public will work. In my opinion the right way is to use the AddRange method in the DefaultFeedItemNormalizer class to add the images. Its up to you Rob ;)

**Comment by RobThree** [comment]
`AddRange` implies an `IList` implementation, we have an `IEnumerable` which may not even implement an `AddRange` 😉

**Comment by keesdewit82** [comment]
Whoops you got me there :)

**Pull request merged**
