### PR TITLE
load Feed from raw XML

### PR DESCRIPTION
**Pull request by RouR**
New feature.
In some cases RSS content must be loaded with user credentials.With this feature, it became to possible realize custom downloading and use this library just for parsing.

### CODE REVIEW

**Comment by RobThree** [comment]
Hmmm, this PR causes some (unnecessary) code duplication; with some refactoring that should be easily solved. I'll look into this after dinner and propose a, what I think is a, better solution. But thanks for the idea / PR :+1:

**Comment by RobThree** [comment]
I added two overloads (`RetrieveFeed(XmlReader xmlReader)` and `RetrieveFeed(XmlReader xmlReader, IFeedItemNormalizer normalizer)`) so that you can pass in an `XmlReader` (which you can, in turn, feed with a string if you so desire). I think this approach is cleaner, do you agree?

I can/will release an update to the NuGet package if you want to.

**Comment by RobThree** [comment]
> I can/will release an update to the NuGet package if you want to.

As a matter of fact: [I just did](https://www.nuget.org/packages/SimpleFeedReader/1.0.4) :smirk:

**Comment by RouR** [comment]
Thank`s

**Pull request closed without merging**
